### ISSUE TITLE
Please add insuline intake.

### ISSUE THREAD

**Issue by acesuares** [Glucosio/glucosio-android#207] opened 2016-02-18 23:11 UTC
Hi there,

As I am measuring glucose levels several times a day, and register them in Glucosio, it would be nice to also be able to add insuline intake in the same app. It would be even better maybe, to differentiate between slow and fast insuline, i.e. levemir and novorapid, which are commonly prescribed in our country.

If I can be of any help !?

**Comment by PaoloRotolo** [comment] 2016-04-06 17:58
@satya164, @elioqoshi I need some design tips on this. I guess we can't just add another button in our expandable Floating Action button, because on smaller phone it will look bad and go out of screen.

@bkerensa Do you think we can add insuline intake as a parameter in Glucose activity?

**Comment by acesuares** [comment] 2016-04-06 18:48
Maybe add it in glucose measurement? Most time I  measure and then determine intake. So, could this work: 
* 120, 16 (120 measured, 16 units intake)
* 120, 0 (measurement but intake 0)
*  0, 16 (no measurement but intake 16). 

In that way you wouldn't have to make an extra button...

**Comment by HarKoss** [comment] 2016-07-09 13:44
Hi,

acesuares proposal is a good idea. 
Floating Action buttons could be divided into meta categories, that match user activities or data entrance need. For exemple:
 + Before Physical activity
	parameters: Glycemy measured, whish exercise, how long, ...
 + After Physical activity
	parameters:  Glycemy measured, whish exercise, how long, ...
 + Before meal
 	parameters: Glycemy measured, Glucose intake, delayed insulin intake, regular insulin intake, ...
 + After meal
 	parameters: Glycemy measured, Glucose intake, delayed insulin intake, regular insulin intake, ...
 + Other physical measurement
	parameters: ketones, Weight, Pressure, Cholesterol, A1C, ...

How do you feel about it?

Regards,

p.s. will be happy to participate as developer ;-)

**Comment by acesuares** [comment] 2016-07-09 14:33
Or make the buttons configurable, so the user only sees the one he/she needs...

**Comment by HarKoss** [comment] 2016-07-09 16:18
Isn't this a doublon of #74 ?

**Comment by betsythefc** [comment] 2016-07-20 20:25
I like the idea @acesuares brings up. If there were one more text field for me to enter my insulin intake into, and a dropdown or text box for the type of insulin.

**Comment by bkerensa** [comment] 2016-07-22 08:48
Closing this as it is a duplicate of Bug #74

**Closed by bkerensa** 2016-07-22 08:48 UTC
Labels: feature request, P1
