### ISSUE TITLE
“You already have an entry for this time” displayed every time

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#201] opened 2016-01-21 11:53 UTC
Latest version 0.9.3 via Google Play. Add glucose reading dialog. Enter any reading. Press Done or Back to dismiss the soft keyboard. Click the FAB (you have to dismiss the keyboard first to see it). Get snackbar about already having a reading for that time. The glucose reading dialog remains open even after clicking on the FAB. Clicking on FAB again has no effect, clicking back  takes you out of the dialog. Reading has indeed been recorded so no dataloss. Happens every time.

**Comment by bkerensa** [comment] 2016-01-25 21:48
@PaoloRotolo is this resolved?

**Comment by PaoloRotolo** [comment] 2016-01-29 12:53
I can't reproduce this...

**Comment by Aeyoun** [comment] 2016-02-02 22:44
Installed a new copy on my [admittedly mostly unused] Android tablet, and the same issue happens every time with a clean setup there too.

**Comment by PaoloRotolo** [comment] 2016-02-02 23:11
Can you explain better the bug? Maybe attach some pics. Thanks!

**Comment by Aeyoun** [comment] 2016-02-03 00:01
1. Open the app
2. Click the FAB and select Blood Glucose Level
3. Click on Concentration to bring up the keyboard (keyboard is not visible by default)
4. Enter a test value
5. Since the FAB is now underneath the keyboard, you must either press Done on the softkeyboard or the Back button to dismiss the keyboard
6. Still on the add reading screen, so click the FAB

Expected: Save value and close add reading dialog.
Actual: Value is saved, but snackbar is shown and add reading dialog remain open.

**Comment by TimothyCuffe** [comment] 2016-02-08 01:35
I can reproduce

Device: A0001
OS: Cyanogen 12.1.1 (android base 5.1.1)
From: Google play

**Comment by PaoloRotolo** [comment] 2016-03-05 16:16
This should be fixed in latest daily build.
Let me know. 
http://daily.glucosio.org/

**Comment by PaoloRotolo** [comment] 2016-03-05 16:36
BTW, the issue was a duplicate method in mmol/L module. That's why I didn't notice it before: I was looking for it with mg/dL.

**Closed by PaoloRotolo** 2016-03-05 16:36 UTC
Labels: 3 - Done, bug, P1, production
